# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Julia Venturini
email: julia.venturini@issibern.ch
author: Julia Venturini
copyright: Copyright © 2020
description: >- # this means to ignore newlines until "baseurl:"
  Personal page of astrophysicist Julia Venturini

baseurl: "" # the subpath of your site, e.g. /blog
url: "jventu.github.io/julias-page" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%d %b %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
theme: jekyll-theme-yat

# this is used to display publications in the right categories order
# be sure to match default category names defined in site.defaults
publications-categories:
  - "First Author"
  - "Co-Author"
  - "Conference proceedings"

# If you want to change site language, you can set lang option
#  lang: "en"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     text: English
# 
#   - lang: es
#     text: Spanish
#
#   - lang: fr
#     img: https://www.countryflags.io/fr/flat/64.png
#     text: Franch
#
#   - lang: zh-CN
#     img: https://www.countryflags.io/cn/flat/64.png
#     text: Chinese(Simple)
#
#   - lang: zh-TW
#     img: https://www.countryflags.io/tw/flat/64.png
#     text: Chinese(Traditional)
#
#   - lang: ja
#     img: https://www.countryflags.io/jp/flat/64.png
#     text: Japan
#
#   - lang: ko
#     img: https://www.countryflags.io/kr/flat/64.png
#     text: Korean
#
#   - lang: ru
#     img: https://www.countryflags.io/ru/flat/64.png
#     text: Russia

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
theme_color: coolblack
#
# Custom color as below:
# theme_color: "#090a0b"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - about.html
  - CV.html
  - publications.html
  

# Page default value
# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

# Pagination setting
# paginate: 5

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"


# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
